---
- name: Desktop Experience
  hosts: all
  tasks:
    - name: Desktop Experience
      win_feature:
          name: Desktop-Experience
          state: Present
          include_sub_features: True
      when: ('2008' in ansible_os_name) or ('2012' in ansible_os_name)
...