---
- name: Deploy MS .Net 4.5
  hosts: windows
  tasks:
    - name: Create temp deploy dir
      win_file:
        path: "C:\\deploy"
        state: "directory"
    - name: Download dotNet 4_5 full exe
      win_get_url:
        dest: "C:\\deploy\\dotnet 4_5 Full Download.exe"
        url: "https://download.microsoft.com/download/E/2/1/E21644B5-2DF2-47C2-91BD-63C560427900/NDP452-KB2901907-x86-x64-AllOS-ENU.exe"
        force: no
    - name: Install dotNet 4_5
      win_dotnet:
        src: "C:\\deploy\\dotnet 4_5 Full Download.exe"
        version: '4'
...