---
- name: Local Admin
  hosts: all
  tasks:
  - block:
    - name: Check for Local Administrator, rename if found
      win_user:
        name: administrator
        state: absent
    rescue:
    - name: Rename local admin 2012/2008
      win_shell: wmic useraccount where "name='Administrator'" rename Chancellor
      when: ('2008' in ansible_os_name) or ('2012' in ansible_os_name)
    - name: Rename local admin 2016
      win_shell: Rename-LocalUser -name administrator -newname chancellor
      when: ('2016' in ansible_os_name)

  - name: Check for & Configure Chancellor
    win_user:
      name: chancellor
      state: present
      password: ""
      update_password: on_create
      groups: Administrators
      groups_action: replace
...