---
- name: Local Admin
  hosts: windows
  tasks:
    - name: Check Local Admin doesn't exist
      win_user:
        name: administrator
        state: absent

    - name: Check for Chancellor
      win_user:
        name: chancellor
        state: present
        password: "C@ri!i0n"
        update_password: on_create
        groups: Administrators
        groups_action: replace
...